name: Deploy

on:
  push:
    branches:
      - master
      - deploy-fix

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/deploy-fix'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: SCP Command to Transfer Files to Remote Server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.PUBLISH_SSH_HOST }}
          port: ${{ secrets.PUBLISH_SSH_PORT }}
          username: ${{ secrets.PUBLISH_SSH_USER }}
          key: ${{ secrets.PUBLISH_SSH_KEY }}
          publish_dir: ./dist
          source: "dist/*"
          target: "/docker/webxl"



